name: CI Pipeline
run-name: ${{github.actor}} is running CI for ${{github.repository}}
on: 
    push:
        branches:
            - main
        paths:
            - 'wisecow/**'
            - '.github/workflows/**'
            - 'Dockerfile'
            
jobs:
    checkout-the-code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Give permissions to Wisecow Script
              run: chmod +x ./wisecow/wisecow.sh
              shell: bash


            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{vars.DockerHub_Username}}
                password: ${{secrets.DockerHub_Token}}
            
            - name: set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: set up docker buildx
              uses: docker/setup-buildx-action@v3

            - name: build and push
              uses: docker/build-push-action@v6
              with:

                push: true
                tags: |
                      ${{vars.DockerHub_Username}}/wisecow:${{github.sha}}
                      ${{vars.DockerHub_Username}}/wisecow:latest
                context: .
                file: ./Dockerfile
                

            